language: bash

sudo: false

git:
    depth: 200

env:
    global:
        - PATH=$PATH:$HOME/bin

    matrix:
        - XLINT=1
        - ARCH=x86_64 BOOTSTRAP=x86_64
        - ARCH=i686 BOOTSTRAP=i686
        - ARCH=armv6hf BOOTSTRAP=x86_64
        - ARCH=armv7hf BOOTSTRAP=x86_64
        - ARCH=x86_64-musl BOOTSTRAP=x86_64-musl
        - ARCH=armv7hf-musl BOOTSTRAP=x86_64-musl
        - ARCH=armv6hf-musl BOOTSTRAP=x86_64-musl

before_script:
    - common/travis/prepare.sh
    - common/travis/fetch_upstream.sh
    - common/travis/changed_templates.sh
    - common/travis/xlint.sh
    - common/travis/bootstrap.sh $BOOTSTRAP

script:
    - common/travis/build.sh $BOOTSTRAP $ARCH

after_script:
    - common/travis/show_files.sh $BOOTSTRAP $ARCH

notifications:
    email: false
