name: "Push Notification"
on:
  push:
    branches: [master]

jobs:
  ircnotify:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Shorten URL
        id: shortener
        if: github.repository == 'void-linux/void-packages'
        uses: Gottox/url-shortener-action@master
        with:
          url: "${{ github.event.compare }}"
      - name: "Push Notification"
        uses: Gottox/irc-message-action@master
        continue-on-error: true
        if: github.repository == 'void-linux/void-packages'
        with:
          notice: true
          channel: "#xbps"
          nickname: void-packages
          sasl_password: ${{ secrets.freenode_password_void_packages }}
          tls: true
          message: >-
            ${{ github.actor }}
            pushed
            ${{ steps.shortener.outputs.short_url }}
